# Generated by Django 4.0.4 on 2022-06-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'team'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
    ]
